<div style="border-left: 8px solid #1A365D; border-right: 2px solid #E2E8F0; border-top: 2px solid #E2E8F0; border-bottom: 2px solid #E2E8F0; padding: 25px; border-radius: 4px; background-color: #F8FAFC; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
    <span style="color: #D69E2E; font-weight: bold; letter-spacing: 1.5px; font-size: 0.9em; text-transform: uppercase;">FES Acatlán • UNAM</span>
    <h1 style="color: #1A365D; font-size: 2.2em; font-weight: 700; margin-top: 5px; margin-bottom: 5px; line-height: 1.2;">Diplomado en Técnicas Estadísticas y Minería de Datos</h1>
    <h3 style="color: #4A5568; font-size: 1.3em; font-weight: 400; margin-top: 0; margin-bottom: 20px;">Módulo II: Modelos Estadísticos</h3>
    <hr style="border: 0; height: 1px; background: #CBD5E0; margin-bottom: 20px;">
    <table style="width: 100%; border-collapse: collapse; font-size: 0.95em; color: #4A5568;">
        <tr>
            <td style="padding: 4px 0; width: 50%;"><strong>Notebook:</strong> Introducción a Python</td>
            <td style="padding: 4px 0; width: 50%; text-align: right;"><strong>Estudiante:</strong> Blanca Sánchez Germán</td>
        </tr>
        <tr>
            <td style="padding: 4px 0;"><strong>Profesora:</strong> Act. Claudia C. Reyes Montes de Oca</td>
            <td style="padding: 4px 0; text-align: right;"><strong>Fecha:</strong> 17 de Junio 2026</td>
        </tr>
    </table>
</div>

# Python: Fundamentos y Herramientas de Cómputo

Python es un lenguaje de programación de alto nivel creado por **Guido van Rossum** a inicios de los noventa. Su filosofía se centra firmemente en la legibilidad del código, lo que permite a los desarrolladores expresar conceptos en pocas líneas en comparación con lenguajes como C++ o Java.

### Pilares Fundamentales:

- **Paradigma Orientado a Objetos:** En Python, prácticamente **todo es un objeto** (desde un número entero hasta una función o un módulo). Esto significa que cada elemento posee atributos (datos) y métodos (funciones integradas).
- **Tipado Dinámico:** Las variables no están amarradas a un tipo de dato estático. El intérprete deduce el tipo en tiempo de ejecución, permitiendo reasignar una variable libremente.
- **Naturaleza Interpretada:** No requiere compilación previa. El código se procesa línea por línea, lo cual encaja perfectamente con el flujo de trabajo interactivo de Jupyter Notebooks.

| Ventajas | Desventajas |
| :--- | :--- |
| Sintaxis limpia, intuitiva y cercana al lenguaje humano | Ejecución más lenta en tareas puramente secuenciales que C |
| Ecosistema gigante para Ciencia de Datos y Estadística | Mayor consumo de memoria por la gestión dinámica de objetos |

## 1. Tipos de Datos y Formateo Dinámico de Texto

Python maneja de forma nativa estructuras simples:
- **Numéricos:** `int` (enteros), `float` (decimales) y `complex` (complejos).
- **Cadenas (`str`):** Secuencias de caracteres inmutables.
- **Booleans (`bool`):** Valores lógicos `True` o `False`.

In [1]:
#esto es una cadena 
usuario = "Blanca"
carrera = "Actuaria"

In [2]:
print("Estudiante: {} | Programa: {}".format(usuario, carrera))

Estudiante: Blanca | Programa: Actuaria

In [3]:
print("Estudiante: {}\nPrograma: {}".format(usuario, carrera)) # con salto de linea

Estudiante: Blanca
Programa: Actuaria

In [4]:
print("Estudiante: {}\tPrograma: {}".format(usuario, carrera))

Estudiante: Blanca	Programa: Actuaria

In [5]:
#esto es un entero 
e = 23 
e

23

### Verificación de Tipos en Tiempo de Ejecución
Podemos evaluar la identidad de los datos usando `type()` o validar compatibilidades con `isinstance()`:

`type()` es una función de Python que permite saber el tipo de un objeto, es decir, responde a ¿de qué tipo es esto?. Es una estructura `type(objeto)`

Por ejemplo:

```python
type(5)        # int
type(3.14)     # float
type("Hola")   # str
type([1,2,3])  # list
type({'a':1})  # dict

In [6]:
type(5)

int

In [7]:
type(3.14)

float

In [8]:
type("Hola")

str

In [5]:
# Inspección directa
print("Tipo de dato:", type(2026))

# Validación lógica de tipos
es_cadena = isinstance(usuario, str)
print(f"¿La variable 'usuario' es un string?: {es_cadena}")

Tipo de dato: <class 'int'>
¿La variable 'usuario' es un string?: True

## Operadores en Python

Los operadores aritméticos en Python se utilizan para realizar operaciones matemáticas básicas. A continuación se presentan los más comunes, con ejemplos y explicaciones detalladas.

### 1. Suma
Suma dos números. Si se usan con cadenas, las concatena, pero en este contexto nos centramos en numéricos.

```python
# Suma de enteros
s = 3 + 2
print(s) 

# Suma de flotantes
s2 = 2.5 + 1.5
print(s2)  

# Mezcla de tipos: el resultado es flotante
s3 = 3 + 2.0
print(s3) 
```

### 2. Resta
Resta el segundo número del primero.

```python
r = 4 - 7
print(r)  # -3

# Con flotantes
r2 = 10.5 - 3.2
print(r2)  # 7.3
```

### 3. Negación (`-` como operador unitario)
Cambia el signo de un número.

```python
n = -7
print(n)  # -7

# También puede aplicarse a variables
x = 5
y = -x
print(y)  # -5
```

### 4. Multiplicación (`*`)
Multiplica dos números.

```python
m = 2 * 6
print(m)  # 12

# Con flotantes
m2 = 2.5 * 4
print(m2)  # 10.0
```

### 5. Exponente (`**`)
Eleva el primer número a la potencia del segundo.

```python
e1 = 2 ** 6
print(e1)  # 64

# Exponentes con flotantes
e2 = 9 ** 0.5  # raíz cuadrada
print(e2)  # 3.0

# Exponentes negativos
e3 = 2 ** -1
print(e3)  # 0.5
```

### 6. División (`/`)
Realiza la división y siempre devuelve un número flotante (decimal), incluso si los operandos son enteros.

```python
d = 3.5 / 2
print(d)  # 1.75

# División de enteros produce flotante
d2 = 7 / 2
print(d2)  # 3.5

# División entre cero genera error
# d3 = 5 / 0  # ZeroDivisionError
```

### 7. División entera (`//`)
Devuelve la parte entera del cociente (truncamiento hacia abajo, no redondeo). Es decir, el resultado es el mayor entero menor o igual al cociente exacto.

```python
de = 3.5 // 2
print(de)  # 1.0  (porque 3.5/2 = 1.75, parte entera 1)

# Con números negativos, el truncamiento es hacia abajo
de2 = -3.5 // 2
print(de2)  # -2.0  (porque -3.5/2 = -1.75, el mayor entero menor o igual es -2)

# División entera entre enteros da entero
de3 = 7 // 2
print(de3)  # 3
```

### 8. Operador módulo (`%`)
Devuelve el resto de la división entre dos números. Es muy útil para saber si un número es par o múltiplo de otro.

```python
mod = 7 % 2
print(mod)  # 1  (porque 7 dividido 2 da 3, y resto 1)

# Otros ejemplos
print(10 % 3)  # 1
print(15 % 5)  # 0  (múltiplo)
print(8 % 3.5) # 1.0 (con flotantes)

# Con números negativos, el signo del resto sigue al divisor
print(-7 % 2)  # 1  (en Python, el resto siempre es no negativo)
```

#### Consideraciones adicionales

- **Prioridad de operadores**: Siguen las reglas matemáticas habituales (potencia antes que multiplicación/división, y estas antes que suma/resta). Se pueden usar paréntesis para cambiar el orden.
- **Tipos de datos**: Al mezclar enteros y flotantes, el resultado suele ser flotante.
- **Errores comunes**: División por cero, o esperar un entero en división normal.

Los valores booleanos también resultan de comparaciones entre valores.

| Operador | Descripción                  | Ejemplo             | Resultado |   
|----------|------------------------------|---------------------|-----------|
| `==`     | ¿Son iguales a y b?          | `r = 5 == 3`        | `False`   |
| `!=`     | ¿Son distintos a y b?        | `r = 5 != 3`        | `True`    |
| `<`      | ¿Es a menor que b?           | `r = 5 < 3`         | `False`   |
| `>`      | ¿Es a mayor que b?           | `r = 5 > 3`         | `True`    |
| `<=`     | Menor o igual que            | `5 <= 5`            | `True`    |
| `>=`     | Mayor o igual que            | `5 >= 3`            | `True`    |

In [11]:
miTexto = "Hola"

In [13]:
m = "02"

In [17]:
concatenacion = miTexto + m
concatenacion

'Hola02'

In [6]:
# Demostración de precedencia alterada por paréntesis
calculo_A = 10 + 2 * 5 ** 2   # Potencia primero -> Multiplicación -> Suma (Resultado: 60)
calculo_B = (10 + 2) * 5 ** 2 # Paréntesis primero (Resultado: 300)
print(f"Resultado A: {calculo_A} \nResultado B: {calculo_B}")

# Uso de operadores lógicos condicionales (not, and, or)
proyecto_entregado = True
nota_minima = False
aprobado = proyecto_entregado or nota_minima  # Basta con que uno sea verdadero
print("¿Materia aprobada?:", aprobado)

Resultado A: 60
Resultado B: 300
¿Materia aprobada?: True

## Listas en Python

Las **listas** son una de las estructuras de datos más versátiles y utilizadas en Python. Nos permiten almacenar una colección de elementos (que incluso pueden ser de diferentes tipos, como números y texto) en una sola variable.

**Características principales:**
* Se definen utilizando corchetes `[ ]` y separando sus elementos con comas.
* Tienen un orden específico (podemos acceder a sus elementos por su posición).
* Son mutables (podemos modificar sus elementos después de crearla).

**Comportamiento con operadores matemáticos:**
A diferencia de los vectores matemáticos, los operadores en las listas nativas de Python tienen un comportamiento enfocado en la estructura, no en el cálculo aritmético:
* El operador `*` **repite** los elementos de la lista.
* El operador `+` sirve para **concatenar** (unir) dos listas, por lo que intentar sumar un número entero directamente a una lista nos arrojará un error de tipo (`TypeError`).

In [8]:
# Creación y alteración de listas
lenguajes = ["R", "SQL", "C++"]
lenguajes.insert(0, "Python")  # Añade al inicio del índice
lenguajes.pop()                # Remueve el último elemento ("C++")
print("Lista resultante:", lenguajes)

# Slicing avanzado sobre una secuencia numérica
serie_numerica = list(range(20))
print("Sublista (índices del 5 al 11):", serie_numerica[5:12])
print("Inversión total de la lista:", serie_numerica[::-1])

Lista resultante: ['Python', 'R', 'SQL']
Sublista (índices del 5 al 11): [5, 6, 7, 8, 9, 10, 11]
Inversión total de la lista: [19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [9]:
miL =[1, "Hola", 3.1415 ]

In [10]:
miL * 3 #REPSTIR LA LISTA 3 VECES

[1, 'Hola', 3.1415, 1, 'Hola', 3.1415, 1, 'Hola', 3.1415]

In [11]:
lista =[1, 2, 3, 4, 5]

In [12]:
miL + lista # concatenar dos lsitas

[1, 'Hola', 3.1415, 1, 2, 3, 4, 5]

In [7]:
miL + 10 #sale error porque no podemos concatenar un entero solo listas

NameError: name 'miL' is not defined

In [30]:
# Accedemos al primero elemento de la lista 
miL[2] #[0] es el primer elemento dee la lista y [1] es el segundo elemnto de la lista

3.1415

In [31]:
# A mi primer elemento de la lista, le podemos poner 5 
miL [0] + 5

6

In [32]:
mi = [ 'Blanca', 'Sanchez']
mi

['Blanca', 'Sanchez']

## Librerias

### Numpy (Numerical Python) - Vectores y Matrices

Las listas de Python no están diseñadas para operaciones matemáticas directas elemento a elemento. Para ello usamos **NumPy**, que introduce el concepto de **vectorización**: ejecutar cálculos matemáticos masivos en bloques contiguos de memoria de manera asombrosamente veloz.

NumPy es la biblioteca fundamental para la computación científica en Python. Proporciona un objeto de arreglo multidimensional de alto rendimiento y herramientas para trabajar con estos arreglos. Si alguna vez has trabajado con MATLAB, encontrarás muchas similitudes.

El corazón de NumPy es el arreglo (array) , una estructura de datos que almacena elementos del mismo tipo (generalmente números) de forma contigua en memoria. Esto permite realizar operaciones matemáticas extremadamente rápidas, ya que las operaciones se ejecutan en C en lugar de en bucles de Python.

Para usar NumPy, primero debemos importarlo. Por convención, se importa como `np`:

In [33]:
# Importamos la libreria Numpy
#Import libreria as alias

In [36]:
#Importamos la libreria Numpy
import numpy as np

In [35]:
# Si no se tiene instalado 
# !pip install libreria

In [37]:
# A partir de una lista, puedo crear un arreglo de Numpy 
lista = [1, 2, 3, 4, 5]
arreglo = np.array (lista)

print (arreglo)

[1 2 3 4 5]

In [38]:
type(lista)

list

In [39]:
type(arreglo)

numpy.ndarray

### Creación de arreglos básicos

In [13]:
import numpy as np

# Creación de arreglos matriciales mediante distribución aleatoria y rangos
matriz_identidad_mod = np.eye(3) * 5       # Matriz con 5s en la diagonal principal
datos_normales = np.random.normal(loc=0, scale=1, size=(3, 3)) # Distribución Gaussiana

print("Matriz Diagonal:\n", matriz_identidad_mod)
print("\nMatriz Gaussiana 3x3:\n", datos_normales)

# Multiplicación de matrices usando el operador moderno '@'
matriz_A = np.array([[2, 4], [1, 3]])
matriz_B = np.array([[5, 0], [2, 1]])
producto_matricial = matriz_A @ matriz_B
print("\nResultado del Producto Matricial:\n", producto_matricial)

Matriz Diagonal:
 [[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]

Matriz Gaussiana 3x3:
 [[ 0.17399958  0.7271153  -0.47807764]
 [-0.74924806 -0.01231915  0.49698945]
 [-1.21022154  0.44987948  0.80232365]]

Resultado del Producto Matricial:
 [[18  4]
 [11  3]]

In [26]:
# Crear un arreglo unidimensional (vector) a partir de una lista
vector = np.array([1, 2, 3, 4, 5])
print("Vector:", vector)

# Crear un arreglo bidimensional (matriz)
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz:\n", matriz)

# Funciones útiles para crear arreglos
ceros = np.zeros((3, 4))        # Matriz de 3x4 llena de ceros
unos = np.ones((2, 3))           # Matriz de 2x3 llena de unos
rango = np.arange(0, 11, 2)      # Similar a range() pero devuelve un arreglo: [0, 2, 4, 6, 8, 10] (no llega hasta 11)
lineal = np.linspace(0, 1, 5)    # 5 puntos espaciados uniformemente entre 0 y 1: [0., 0.25, 0.5, 0.75, 1.]
identidad = np.eye(3)             # Matriz identidad de 3x3

print("\nCeros:\n", ceros)
print("Unos:\n", unos)
print("Rango:", rango)
print("Lineal:", lineal)
print("Identidad:\n", identidad)

Vector: [1 2 3 4 5]
Matriz:
 [[1 2 3]
 [4 5 6]]

Ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Unos:
 [[1. 1. 1.]
 [1. 1. 1.]]
Rango: [ 0  2  4  6  8 10]
Lineal: [0.   0.25 0.5  0.75 1.  ]
Identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### Operaciones matemáticas básicas

Una de las mayores ventajas de NumPy es que permite realizar operaciones vectorizadas. En lugar de escribir bucles, las operaciones se aplican elemento por elemento automáticamente.

#### Operaciones aritméticas elemento a elemento

In [14]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

# Operaciones aritméticas
print("Suma:", a + b)          # [11 22 33 44]
print("Resta:", a - b)          # [9 18 27 36]
print("Multiplicación:", a * b)  # [10 40 90 160]
print("División:", a / b)        # [10. 10. 10. 10.]
print("Potencia:", a ** 2)       # [100 400 900 1600]

# También con escalares
print("Multiplicar por escalar:", a * 2)  # [20 40 60 80]

Suma: [11 22 33 44]
Resta: [ 9 18 27 36]
Multiplicación: [ 10  40  90 160]
División: [10. 10. 10. 10.]
Potencia: [ 100  400  900 1600]
Multiplicar por escalar: [20 40 60 80]

#### Operaciones de agregación (suma, producto, etc.)

In [8]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz original:\n", matriz)

print("Suma total:", np.sum(matriz))           # 21
print("Suma por columnas (eje 0):", np.sum(matriz, axis=0))  # [5 7 9]
print("Suma por filas (eje 1):", np.sum(matriz, axis=1))     # [6 15]

print("Media total:", np.mean(matriz))          # 3.5
print("Mínimo:", np.min(matriz))                # 1
print("Máximo:", np.max(matriz))                # 6
print("Desviación estándar:", np.std(matriz))   # 1.7078...

Matriz original:
 [[1 2 3]
 [4 5 6]]
Suma total: 21
Suma por columnas (eje 0): [5 7 9]
Suma por filas (eje 1): [ 6 15]
Media total: 3.5
Mínimo: 1
Máximo: 6
Desviación estándar: 1.707825127659933

Además, NumPy incluye un submódulo llamado `linalg` para operaciones de álgebra lineal y también ofrece funciones estadísticas rápidas y eficientes (mean, std).

In [38]:
# Importamos la libreria
import numpy as np

## Análisis de Datos Estructurados con Pandas

**Pandas** nos permite extraer e interrogar la información en `DataFrames`. Para este ejemplo, simularemos un set de datos de rendimiento de estudiantes de manera vectorizada.

Es una libreria que facilita el manejo de datos estructurados
- tablas o bases de datos
- series de tiempo
- archivos csv, excel
Para el análisis de datos

In [40]:
import pandas as pd

In [63]:
edades = np.array ([25, 30, 35, 40, 45 ])
peso = np.array ([ 60, 70, 80, 90, 100 ])
estatura = np.array ([1.60, 1.65, 1.70, 1.75, 1.80])
IMC = peso / ( estatura ** 2)

In [64]:
df= pd.DataFrame ([edades, peso, estatura, IMC])
df

         0          1          2          3           4
0  25.0000  30.000000  35.000000  40.000000   45.000000
1  60.0000  70.000000  80.000000  90.000000  100.000000
2   1.6000   1.650000   1.700000   1.750000    1.800000
3  23.4375  25.711662  27.681661  29.387755   30.864198

In [65]:
# Vamos a crear un diccionario 
# { key: valor}

diccionario = {' Edad': edades, 'Peso' : peso, 'Estatura': estatura, 'IMC': IMC}
diccionario

{' Edad': array([25, 30, 35, 40, 45]),
 'Peso': array([ 60,  70,  80,  90, 100]),
 'Estatura': array([1.6 , 1.65, 1.7 , 1.75, 1.8 ]),
 'IMC': array([23.4375    , 25.71166208, 27.6816609 , 29.3877551 , 30.86419753])}

In [72]:
df1 = pd.DataFrame(diccionario)
df1

    Edad  Peso  Estatura        IMC
0     25    60      1.60  23.437500
1     30    70      1.65  25.711662
2     35    80      1.70  27.681661
3     40    90      1.75  29.387755
4     45   100      1.80  30.864198

In [74]:
#Si quiero personas mayores de 30 años 
# 1. Corregimos los nombres de las columnas quitando el espacio rebelde
df1.columns = ['Edad', 'Peso', 'Estatura', 'IMC']
# 2. Aplicamos el filtro exactamente como lo escribió la maestra
e30 = df1[df1['Edad'] > 30]
# 3. Mostramos el resultado en pantalla
e30

   Edad  Peso  Estatura        IMC
2    35    80      1.70  27.681661
3    40    90      1.75  29.387755
4    45   100      1.80  30.864198

In [75]:
#Si quiero personas mayores de 30 años 
em30 = df1[df1['Edad'] <= 30 ] 
em30

   Edad  Peso  Estatura        IMC
0    25    60      1.60  23.437500
1    30    70      1.65  25.711662

In [79]:
condicion1 = df1[(df1['Edad'] <= 28)&(df1['Peso'] < 65)]
condicion1

   Edad  Peso  Estatura      IMC
0    25    60       1.6  23.4375

In [15]:
import pandas as pd

# Vectores numéricos independientes
id_alumnos = np.array([101, 102, 103, 104, 105])
horas_estudio = np.array([12, 18, 5, 22, 15])
calificacion_base = np.array([75, 88, 60, 95, 70])

# Cálculo vectorizado: Ajustamos la calificación según horas de estudio
calificacion_final = calificacion_base + (horas_estudio * 0.2)
calificacion_final = np.clip(calificacion_final, 0, 100) # Forzamos a que el límite máximo sea 100

# Construcción del DataFrame a partir de un diccionario
df_estudiantes = pd.DataFrame({
    'ID': id_alumnos,
    'Horas_Estudio': horas_estudio,
    'Nota_Base': calificacion_base,
    'Nota_Final': calificacion_final
})

df_estudiantes

    ID  Horas_Estudio  Nota_Base  Nota_Final
0  101             12         75        77.4
1  102             18         88        91.6
2  103              5         60        61.0
3  104             22         95        99.4
4  105             15         70        73.0

### Segmentación Dinámica y Filtros Booleanos

Para interrogar al DataFrame bajo múltiples condiciones, usamos operadores bitwise (`&` para AND, `|` para OR) y obligatoriamente aislamos cada bloque con paréntesis.

In [18]:
# Filtro 1: Estudiantes que dedicaron más de 14 horas al estudio
alto_esfuerzo = df_estudiantes[df_estudiantes['Horas_Estudio'] > 14]
print("Alumnos con Alto Esfuerzo ")
display(alto_esfuerzo)  #

# Filtro 2: Alumnos con una Nota_Base menor a 80 PERO que alcanzaron una Nota_Final mayor o igual a 75
filtro_mejora = df_estudiantes[(df_estudiantes['Nota_Base'] < 80) & (df_estudiantes['Nota_Final'] >= 75)]
print("\nAlumnos que repuntaron en la Nota Final")
display(filtro_mejora)  

# Resumen estadístico global del grupo
print("\n Sumario Estadístico Descriptivo")
display(df_estudiantes.describe().T) #  La tabla del resumen estadístico transpuesta

Alumnos con Alto Esfuerzo

    ID  Horas_Estudio  Nota_Base  Nota_Final
1  102             18         88        91.6
3  104             22         95        99.4
4  105             15         70        73.0

Alumnos que repuntaron en la Nota Final

    ID  Horas_Estudio  Nota_Base  Nota_Final
0  101             12         75        77.4

 Sumario Estadístico Descriptivo

               count    mean        std    min    25%    50%    75%    max
ID               5.0  103.00   1.581139  101.0  102.0  103.0  104.0  105.0
Horas_Estudio    5.0   14.40   6.426508    5.0   12.0   15.0   18.0   22.0
Nota_Base        5.0   77.60  14.010710   60.0   70.0   75.0   88.0   95.0
Nota_Final       5.0   80.48  15.219461   61.0   73.0   77.4   91.6   99.4